[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ruff>=0.7.4",
    "selenium>=4.26.1",
    "seleniumbase>=4.32.12",
]
